// <auto-generated />
namespace LandmarkRemark.Entities.Migrations.LandmarkRemarkContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migration_LandmarkRemarkContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration_LandmarkRemarkContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201710161232046_Migration_LandmarkRemarkContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
